def make_word_dict():
    """Read the words in words.txt and return a dictionary
    that contains the words as keys"""
    d = dict()
    fin = open('a.txt')
    for line in fin:
        word = line.strip().lower()
        d[word] = word

    return d

def rotate_word(word, para, rotated = ''):
	for i in word:
		asci =ord(i)
		rotate = asci + para
		rotated += chr(rotate)
	return rotated

def rotate_pairs(word, word_dict):
    """Prints all words that can be generated by rotating word.

    word: string
    word_dict: dictionary with words as keys
    """
    for i in range(1, 14):
        rotated = rotate_word(word, i)
        if rotated in word_dict:
            print word, i, rotated


if __name__ == '__main__':
    word_dict = make_word_dict()

    for word in word_dict:
        rotate_pairs(word, word_dict)

